
export const FETCH_IMAGE_BY_ID_ERROR = 'FETCH_IMAGE_BY_ID_ERROR';
export const FETCH_IMAGE_BY_ID_PENDING = 'FETCH_IMAGE_BY_ID_PENDING';
export const FETCH_IMAGE_BY_ID_SUCCESS = 'FETCH_IMAGE_BY_ID_SUCCESS';

export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FETCH_PRODUCTS_PENDING = 'FETCH_PRODUCTS_PENDING';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';

export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR';
export const FETCH_CATEGORIES_PENDING = 'FETCH_CATEGORIES_PENDING';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const CATEGORY_SELECTED_FILE = 'CATEGORY_SELECTED_FILE';
export const SHOW_ADD_CATEGORY_MODAL = 'SHOW_ADD_CATEGORY_MODAL';

export const  UPLOAD_CATEGORY_NAME = 'UPLOAD_CATEGORY_NAME';
export const UPLOAD_CATEGORY_ERROR = 'UPLOAD_CATEGORY_ERROR';
export const UPLOAD_CATEGORY_SUCCESS = 'UPLOAD_CATEGORY_SUCCESS';
export const UPLOAD_CATEGORY_PENDING = 'UPLOAD_CATEGORY_PENDING';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

